//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UrlItemModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UrlItemModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trunc.Resources.Models.UrlItemModel", typeof(UrlItemModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom URL.
        /// </summary>
        public static string CustomUrl {
            get {
                return ResourceManager.GetString("CustomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be 3 or more characters.
        /// </summary>
        public static string CustomUrlMinLength {
            get {
                return ResourceManager.GetString("CustomUrlMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must use only letters, numbers, - or _.
        /// </summary>
        public static string CustomUrlRegularExpression {
            get {
                return ResourceManager.GetString("CustomUrlRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire in Days.
        /// </summary>
        public static string ExpireInDays {
            get {
                return ResourceManager.GetString("ExpireInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire in Days must be an integer.
        /// </summary>
        public static string ExpireInDaysRange {
            get {
                return ResourceManager.GetString("ExpireInDaysRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Mode.
        /// </summary>
        public static string ExpireMode {
            get {
                return ResourceManager.GetString("ExpireMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin URL.
        /// </summary>
        public static string OriginUrl {
            get {
                return ResourceManager.GetString("OriginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin URL is required.
        /// </summary>
        public static string OriginUrlRequired {
            get {
                return ResourceManager.GetString("OriginUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin URL must be a valid URL.
        /// </summary>
        public static string OriginUrlUrl {
            get {
                return ResourceManager.GetString("OriginUrlUrl", resourceCulture);
            }
        }
    }
}
